### ISSUE TITLE
请问在Linux下怎么运行？

### ISSUE THREAD

**Issue by windskyxb** [Clov614/rewards-helper#1]
root@nanopineo3:/rewaeds# ./rewards-helper
2023/08/06 01:12:12 生成run.bat
2023/08/06 01:12:12 生成run-web.bat
2023/08/06 01:12:12 强烈建议使用run.bat运行本程序
root@nanopineo3:/rewaeds# bash run.bat
run.bat: line 1: start: command not found
root@nanopineo3:/rewaeds# ls
rewards-helper  run.bat  run-web.bat
root@nanopineo3:/rewaeds# start cmd /K rewards-helper
Command 'start' not found, did you mean:
  command 'tart' from deb tart
  command 'rstart' from deb x11-session-utils
  command 'stat' from deb coreutils
  command 'startx' from deb xinit
Try: apt install <deb name>
root@nanopineo3:/rewaeds# bash ./rewards-helper
./rewards-helper: ./rewards-helper: cannot execute binary file
root@nanopineo3:/rewaeds#

**Comment by windskyxb** [comment]
顺便询问一下，有什么方法可以在青龙面板中运行吗？

**Comment by Clov614** [comment]
下载linux的二进制文件： [rewards-helper_linux_amd64.tar.gz](https://github.com/Clov614/rewards-helper/releases/download/v1.0.10/rewards-helper_linux_amd64.tar.gz)
[解压缩](https://www.runoob.com/note/28603)
写一个定时shell [参考](https://zhuanlan.zhihu.com/p/372043390) [参考2](https://cloud.tencent.com/developer/article/2132556)

**Comment by Clov614** [comment]
写好webui，封装为docker应该会比较适用，但是现在程序还太原始了，健壮性太差了

**Comment by Clov614** [comment]
> 顺便询问一下，有什么方法可以在青龙面板中运行吗？

[看了一下这篇文章](https://www.zsxcool.com/29994.html)理论上是可以在青龙面板运行的，但是要多增加一个模式，读取环境变量中的cookies

**Comment by windskyxb** [comment]
> 下载linux的二进制文件： [rewards-helper_linux_amd64.tar.gz](https://github.com/Clov614/rewards-helper/releases/download/v1.0.10/rewards-helper_linux_amd64.tar.gz) [解压缩](https://www.runoob.com/note/28603) 写一个定时shell [参考](https://zhuanlan.zhihu.com/p/372043390) [参考2](https://cloud.tencent.com/developer/article/2132556)

可以使用了，感谢
`root@nanopineo3:/home# wget https://ghproxy.com/https://github.com/Clov614/rewards-helper/releases/download/v1.0.10/rewards-helper_linux_arm64.tar.gz
--2023-08-07 01:48:38--  https://ghproxy.com/https://github.com/Clov614/rewards-helper/releases/download/v1.0.10/rewards-helper_linux_arm64.tar.gz
Resolving ghproxy.com (ghproxy.com)... 144.24.83.236
Connecting to ghproxy.com (ghproxy.com)|144.24.83.236|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3297308 (3.1M) [application/octet-stream]
Saving to: ‘rewards-helper_linux_arm64.tar.gz’

rewards-helper_linux_arm64.tar 100%[=================================================>]   3.14M  1.56MB/s    in 2.0s

2023-08-07 01:48:41 (1.56 MB/s) - ‘rewards-helper_linux_arm64.tar.gz’ saved [3297308/3297308]

root@nanopineo3:/home# tar -zxvf rewards-helper_linux_arm64.tar.gz
LICENSE
README.md
rewards-helper
root@nanopineo3:/home# ls
LICENSE  README.md  rewards-helper  rewards-helper_linux_arm64.tar.gz
root@nanopineo3:/home# ./rewards-helper
2023/08/07 01:55:11 生成run.bat
2023/08/07 01:55:11 生成run-web.bat
2023/08/07 01:55:11 强烈建议使用run.bat运行本程序
root@nanopineo3:/home# ./rewards-helper
2023/08/07 01:55:21 生成默认conf文件中
2023/08/07 01:55:21 [默认不开启代理]
2023/08/07 01:55:21 请将cookies添加至 ./cookie/cookies.txt
2023/08/07 01:55:21 cookie为空,请配置cookie
2023/08/07 01:55:23 长度为0 json格式化失败(疑似Cookie失效)
root@nanopineo3:/home#`
